#!/bin/bash

MOUNTPOINT=/etc/mudskipper/mount
WORKPATH=$(pwd)
DEVICE=

lsblk

echo Select Device for Installation. \(Example: sdx\) \(R\=reload\)
echo ---------------------------------------------------------------
read DEVICE

DEVICE=/dev/$DEVICE

echo Installing Arch-Linux on $DEVICE\? \(y/n\)
echo ------------------------------------------
read answer

echo Enter System Name:
echo ------------------
read Label

umount $DEVICE* &> /dev/null
swapoff $DEVICE* &> /dev/null

sudo dd if=/dev/zero of=$DEVICE bs=1k count=2048 

echo -e "g\nn\n\n\n+512M\nn\n\n\n+1M\nn\n\n\n+2G\nn\n\n\n\nt\n1\n1\nt\n2\n4\nt\n3\n19\nw" | fdisk $DEVICE

mkfs.vfat -F32  ${DEVICE}1
mkswap ${DEVICE}3
mkfs.ext4  -F ${DEVICE}4

e2label ${DEVICE}4 $Label

mkdir -p $MOUNTPOINT

swapon ${DEVICE}3
mount ${DEVICE}4 $MOUNTPOINT
mkdir -p $MOUNTPOINT/boot/EFI
mount ${DEVICE}1 $MOUNTPOINT/boot/EFI

pacstrap /etc/mudskipper/mount base base-devel
pacstrap /etc/mudskipper/mount corn-mirrorlist
read

git clone https://github.com/womba/mudskipper-testing /tmp/mudskipper
cp -R /tmp/mudskipper/* $MOUNTPOINT
rm -R /tmp/mudskipper
echo DEVICE=$DEVICE > /etc/mudskipper/mount/etc/mudskipper/1_Script/config/Mudskipper_Device
echo $WORKPATH
cp $WORKPATH/config/pacman.conf /etc/mudskipper/mount/etc/
read

echo $Label > $MOUNTPOINT/etc/hostname

