#!/bin/bash

source /tmp/Mudskipper_Device

echo $DEVICE
read PLESE KILL ME!
echo 

echo mount drive
read 
cp /etc/mudskipper/1_Script/config/pacman.conf /etc/
read
pacman -Sy

SCRIPTPATH=/etc/mudskipper

#########################
#Installing Bootmanager	#
#########################


pacman -S --noconfirm grub efibootmgr

grub-install --target=x86_64-efi  --efi-directory=/boot/EFI --bootloader-id=grub-efi --removable 
grub-install --target=i386-pc  --boot-directory=/boot --bootloader-id=grub-bios --removable $DEVICE

sed -i "s/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/g" /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg


#########################
#Mkinitcpio Config.	#
#########################


sed -i "s/HOOKS=\"base udev autodetect modconf block filesystems keyboard fsck\"/HOOKS=\"base udev block autodetect modconf filesystems keyboard fsck\"/g" /etc/mkinitcpio.conf
mkinitcpio  -p linux

