#!/bin/bash

#########################
#Arch Install Scripts	#
#########################


pacman --noconfirm -S arch-install-scripts
pacman --noconfirm -S dosfstools

#########################
#Other			#
#########################

pacman --noconfirm -S sudo
pacman --noconfirm -S jre8-openjdk-headless


#########################
#Install X-Server	#
#########################


pacman --noconfirm -S xorg-server 
pacman --noconfirm -S xorg-xinit
pacman --noconfirm -S xorg-server-utils


#########################
#Install Xorg Drivers	#
#########################


pacman --noconfirm -S xorg-drivers


#########################
#Install  Network	#
#########################


pacman --noconfirm -S net-tools
pacman --noconfirm -S ntp
pacman --noconfirm -S avahi


#########################
#Install ACPI		#
#########################


pacman --noconfirm -S acpid


#########################
#Install Cronie		#
#########################


pacman --noconfirm -S cronie


#########################
#Install Audio		#
#########################


pacman --noconfirm -S alsa-utils
pacman --noconfirm -S pulseaudio


#########################
#Install Free Fonts	#
#########################


pacman --noconfirm -S ttf-liberation 
pacman --noconfirm -S ttf-dejavu


#########################
#Install Environment	#
#########################


pacman --noconfirm -S gdm
pacman --noconfirm -S gnome
pacman --noconfirm -S gnome-shell-extension-dash-to-dock
pacman --noconfirm -S gnome-shell-extension-impatience
pacman --noconfirm -S gnome-shell-extension-no-topleft-hot-corner
pacman --noconfirm -S gnome-shell-extension-topicons-plus
pacman --noconfirm -S icons-shadowless

#########################
#CD/DVD Support		#
#########################

pacman --noconfirm -S libcdio 
pacman --noconfirm -S libdvdread 
pacman --noconfirm -S libdvdcss 
pacman --noconfirm -S libdvdnav


#########################
#Multimedia Codecs	#
#########################


pacman --noconfirm -S ffmpeg
pacman --noconfirm -S gst-libav


#########################
#Filesystem Support	#
#########################


pacman --noconfirm -S ntfs-3g
pacman --noconfirm -S exfat-utils 


#########################
#Printer Support	#
#########################

pacman --noconfirm -S cups
pacman --noconfirm -S ghostscript
pacman --noconfirm -S gsfonts
pacman --noconfirm -S system-config-printer


#########################
#Iphone Support		#
#########################


pacman --noconfirm -S ifuse
