#!/bin/bash

#########################
#Arch Install Scripts	#
#########################


pacman --noconfirm -S arch-install-scripts
pacman --noconfirm -S dosfstools

#########################
#Other			#
#########################

pacman --noconfirm -S sudo
pacman --noconfirm -S jre8-openjdk-headless
pacman --noconfirm -S yaourt

#########################
#Install X-Server	#
#########################


pacman --noconfirm -S xorg-server 
pacman --noconfirm -S xorg-xinit
pacman --noconfirm -S xorg-server-utils


#########################
#Install Xorg Drivers	#
#########################


pacman --noconfirm -S xorg-drivers


#########################
#Install  Network	#
#########################


pacman --noconfirm -S net-tools
pacman --noconfirm -S ntp
pacman --noconfirm -S avahi


#########################
#Install ACPI		#
#########################


pacman --noconfirm -S acpid


#########################
#Install Cronie		#
#########################


pacman --noconfirm -S cronie


#########################
#Install Audio		#
#########################


pacman --noconfirm -S alsa-utils
pacman --noconfirm -S pulseaudio


#########################
#Install Free Fonts	#
#########################


pacman --noconfirm -S ttf-liberation 
pacman --noconfirm -S ttf-dejavu


#########################
#Install Environment	#
#########################


pacman --noconfirm -S gdm
pacman --noconfirm -S gnome-shell
pacman --noconfirm -S gnome-shell-extensions
pacman --noconfirm -S gnome-shell-extension-dash-to-dock
pacman --noconfirm -S gnome-shell-extension-impatience
pacman --noconfirm -S gnome-shell-extension-no-topleft-hot-corner
pacman --noconfirm -S gnome-shell-extension-topicons-plus
pacman --noconfirm -S adwaita-icon-theme
pacman --noconfirm -S baobab
pacman --noconfirm -S empathy
pacman --noconfirm -S eog
pacman --noconfirm -S evince
pacman --noconfirm -S gnome-backgrounds
pacman --noconfirm -S gnome-calculator
pacman --noconfirm -S gnome-contacts
pacman --noconfirm -S gnome-control-center
pacman --noconfirm -S gnome-disk-utility
pacman --noconfirm -S gnome-keyring
pacman --noconfirm -S gnome-screenshot
pacman --noconfirm -S gnome-session
pacman --noconfirm -S gnome-settings-daemon
pacman --noconfirm -S gnome-system-monitor
pacman --noconfirm -S gnome-terminal
pacman --noconfirm -S gnome-themes-standard
pacman --noconfirm -S gnome-user-docs
pacman --noconfirm -S gnome-user-share
pacman --noconfirm -S grilo-plugins
pacman --noconfirm -S gtk3-print-backends
pacman --noconfirm -S gvfs
pacman --noconfirm -S gvfs-afc
pacman --noconfirm -S gvfs-goa
pacman --noconfirm -S gvfs-google
pacman --noconfirm -S gvfs-gphoto2
pacman --noconfirm -S gvfs-mtp
pacman --noconfirm -S gvfs-nfs
pacman --noconfirm -S gvfs-smb
pacman --noconfirm -S mousetweaks
pacman --noconfirm -S mutter
pacman --noconfirm -S nautilus
pacman --noconfirm -S networkmanager
pacman --noconfirm -S sushi
pacman --noconfirm -S totem
pacman --noconfirm -S tracker
pacman --noconfirm -S vino
pacman --noconfirm -S xdg-user-dirs-gtk
pacman --noconfirm -S yelp
pacman --noconfirm -S icons-shadowless

#########################
#CD/DVD Support		#
#########################

pacman --noconfirm -S libcdio 
pacman --noconfirm -S libdvdread 
pacman --noconfirm -S libdvdcss 
pacman --noconfirm -S libdvdnav


#########################
#Multimedia Codecs	#
#########################


pacman --noconfirm -S ffmpeg
pacman --noconfirm -S gst-libav


#########################
#Filesystem Support	#
#########################


pacman --noconfirm -S ntfs-3g
pacman --noconfirm -S exfat-utils 


#########################
#Printer Support	#
#########################

pacman --noconfirm -S cups
pacman --noconfirm -S ghostscript
pacman --noconfirm -S gsfonts
pacman --noconfirm -S system-config-printer


#########################
#Iphone Support		#
#########################


pacman --noconfirm -S ifuse
