#!/bin/bash

pacman --noconfirm -Sy arch-install-scripts
pacman --noconfirm -Sy dosfstools
pacman --noconfirm -Sy sudo
pacman --noconfirm -Sy jre8-openjdk-headless
pacman --noconfirm -Sy yaourt
pacman --noconfirm -Sy xorg-server 
pacman --noconfirm -Sy xorg-xinit
pacman --noconfirm -Sy xorg-server-utils
pacman --noconfirm -Sy xorg-drivers
pacman --noconfirm -Sy openssh
pacman --noconfirm -Sy sshfs
pacman --noconfirm -Sy net-tools
pacman --noconfirm -Sy ntp
pacman --noconfirm -Sy avahi
pacman --noconfirm -Sy acpid
pacman --noconfirm -Sy cronie
pacman --noconfirm -Sy alsa-utils
pacman --noconfirm -Sy pulseaudio
pacman --noconfirm -Sy ttf-liberation 
pacman --noconfirm -Sy ttf-dejavu
pacman --noconfirm -Sy libcdio 
pacman --noconfirm -Sy libdvdread 
pacman --noconfirm -Sy libdvdcss 
pacman --noconfirm -Sy libdvdnav
pacman --noconfirm -Sy ffmpeg
pacman --noconfirm -Sy vorbis-tools
pacman --noconfirm -Sy gst-libav
pacman --noconfirm -Sy ntfs-3g
pacman --noconfirm -Sy exfat-utils 
pacman --noconfirm -Sy ifuse
pacman --noconfirm -Sy wget
pacman --noconfirm -Sy git
pacman --noconfirm -Sy bash-completion
pacman --noconfirm -Sy cdrtools
pacman --noconfirm -Sy pulseaudio-alsa
pacman --noconfirm -Sy pulseaudio-bluetooth
pacman --noconfirm -Sy pulseaudio-equalizer
pacman --noconfirm -Sy pulseaudio-gconf
pacman --noconfirm -Sy pulseaudio-jack
pacman --noconfirm -Sy pulseaudio-lirc
pacman --noconfirm -Sy pulseaudio-zeroconf
pacman --noconfirm -Sy pavucontrol
pacman --noconfirm -Sy usb_modeswitch
pacman --noconfirm -Sy modemmanager
pacman --noconfirm -Sy mobile-broadband-provider-info
pacman --noconfirm -Sy nm-connection-editor
pacman --noconfirm -Sy unrar


# Printer

pacman --noconfirm -Sy cups
pacman --noconfirm -Sy cups-pk-helper
pacman --noconfirm -Sy gsfonts
pacman --noconfirm -Sy hplip
pacman --noconfirm -Sy python-gobject
pacman --noconfirm -Sy python-pyqt5
pacman --noconfirm -Sy python2-gnomekeyring
pacman --noconfirm -Sy splix
pacman --noconfirm -Sy system-config-printer
pacman --noconfirm -Sy nss-mdns
