#!/bin/bash


#########################
#Remove Configuration	#
#########################

systemctl enable dhcpcd
systemctl enable ntpd.service
systemctl enable avahi-daemon.service
systemctl enable acpid
systemctl enable cronie
systemctl enable gdm
systemctl enable NetworkManager.service
systemctl enable org.cupsd.service
systemctl enable cups-browsed.service
systemctl enable org.cups.cupsd.service

#########################
#Womba Function		#
#########################

function womba {

git clone https://github.com/womba/$1 /tmp/$1
cp -R /tmp/$1/* /
rm -R /tmp/$1

}

#########################
#Install Packages	#
#########################

womba womba
womba rune-core
womba rune-sounds
#womba rune-app-folder
#womba rune-app-folder-plus
womba rune-bash-profile
womba rune-terminal-color


systemctl enable runecore.service

