#!/bin/bash

USER=
pacman -S --noconfirm sudo
SCRIPTPATH=/etc/mudskipper


function changepass {

if [ "$answer" = "y" ]
then
        CHECK=false

        while [ "$CHECK" = "false" ]
        do

        $SCRIPTPATH/1_Script/ui/clear
        echo ---------------
        echo Enter Password:
        echo ---------------
        read -s PASS1
        $SCRIPTPATH/1_Script/ui/clear
        echo ----------------
        echo Repeat Password:
        echo ----------------
        read -s PASS2

                if [ ! "$PASS1" = "$PASS2" ]
                then

                        $SCRIPTPATH/1_Script/ui/clear
                        echo -----------------------
                        echo Password doesn\'t match
                        echo -----------------------
                else
                        CHECK=true
                        echo $USER:$PASS1 | chpasswd
                        PASS1=1
                        PASS2=2
                        $SCRIPTPATH/1_Script/ui/clear
                        echo ------------
                        echo Password Set
                        echo ------------
                        sleep 1
                fi
        done
fi
}






clear


EXIST=false

#########################
#Setup New User		#
#########################





$SCRIPTPATH/1_Script/ui/clear
echo --------------------------
echo Create a new User? \(y/n\)
echo --------------------------
read answer


while [ "$EXIST" = "false" -o "$answer" = "y" ] 
do



	while [ "$answer"  = "n" -a "$EXIST" = "false" ]
	do

	$SCRIPTPATH/1_Script/ui/clear
	echo ----------------------------------------------------
	echo You need at minimum one user to install this System.
	echo So please enter \(y\).
	echo ----------------------------------------------------
	read answer

	done





	while [ ! "$answer"  = "y" -a ! "$answer" = "n" ]
	do

		$SCRIPTPATH/1_Script/ui/clear
		echo --------------------------------------------
		echo I could not read your answer. Please repeat.
		echo Create a new user? y/n
		echo --------------------------------------------
		read answer
	done


	while [ "$answer" = "y" ]
	do

		$SCRIPTPATH/1_Script/ui/clear
		echo --------------
		echo Enter username
		echo --------------
		read USER
		
		useradd -m -G wheel -s /bin/bash ${USER}
		changepass
		EXIST=true

		gpasswd -a $USER wheel
		gpasswd -a $USER audio
		gpasswd -a $USER video
		gpasswd -a $USER games
		gpasswd -a $USER power

		su $USER  -c "dbus-launch gsettings set org.gnome.desktop.interface icon-theme Sardi"
                su $USER  -c /etc/mudskipper/1_Script/gsett
		
		$SCRIPTPATH/1_Script/ui/clear
		echo ---------------------
		echo Create next User? y/n
		echo ---------------------
        	read answer
	done

done

echo
echo %wheel ALL=\(ALL\) ALL >> /etc/sudoers



#########################
#Set Root Password	#
#########################

USER=root

$SCRIPTPATH/1_Script/ui/clear
echo -----------------------------
echo Set a root Password? \(y\/n\)
echo -----------------------------
read answer

changepass
