#!/bin/bash

if [ !  "$(whoami)" = "root" ]
then
        echo "Please run as root"
	exit
fi

MOUNTPOINT=/etc/mudskipper/mount
SCRIPTPATH=/etc/mudskipper

while [ ! "$ONLINE" = "true" ]
do

wget -q  --timeout=20 --spider http://kernel.org

        if [[ $? -eq 0 ]]; then
                ONLINE=true
		./1_Script/ui/info 2 Online.	
        else
                sleep 1
                ./1_Script/ui/info 1 Please\ check\ your\ internet\ connection.
        fi

done


source ./1_Script/1_Base


arch-chroot $MOUNTPOINT .$SCRIPTPATH/1_Script/2_Boot

arch-chroot $MOUNTPOINT .$SCRIPTPATH/1_Script/3_Set_Language

arch-chroot $MOUNTPOINT .$SCRIPTPATH/1_Script/4_Install_System

arch-chroot $MOUNTPOINT .$SCRIPTPATH/1_Script/5_Install_Environment

arch-chroot $MOUNTPOINT .$SCRIPTPATH/1_Script/6_Install_Applications

arch-chroot $MOUNTPOINT .$SCRIPTPATH/1_Script/7_Enable_Services

mount --bind /home/ $MOUNTPOINT$SCRIPTPATH/3_Bind
arch-chroot $MOUNTPOINT .$SCRIPTPATH/1_Script/8_Create_Users
umount $MOUNTPOINT$SCRIPTPATH/3_Bind

arch-chroot $MOUNTPOINT .$SCRIPTPATH/1_Script/9_Configuration

umount ${DEVICE}1
swapoff ${DEVICE}3
umount ${DEVICE}4
