#!/bin/bash

if [ !  "$(whoami)" = "root" ]
then
        echo "Please run as root"
	exit
fi

MOUNTPOINT=/etc/mudskipper/mount
SCRIPTPATH=/etc/mudskipper

##ooooooooooooooooooooooooooooooooooooooooooooo##
#						#
#		 Mudskipper Core		#
#						#
##ooooooooooooooooooooooooooooooooooooooooooooo##

./1_Script/ui/info 5 Welcome\ to\ Mudskipper
./1_Script/ui/clear
./1_Script/ui/recommend


while [ ! "$ONLINE" = "true" ]
do

wget -q  --timeout=20 --spider http://kernel.org

        if [[ $? -eq 0 ]]; then
                ONLINE=true
		./1_Script/ui/info 2 Online.	
        else
                sleep 1
                ./1_Script/ui/info 1 Please\ check\ your\ internet\ connection.
        fi

done



source ./1_Script/1_Base

##ooooooooooooooooooooooooooooooooooooooooooooo##
#						#
#	Running the Installation Script		#
#						#
##ooooooooooooooooooooooooooooooooooooooooooooo##

##############################
#Download Mudskipper Script  #
##############################

git clone https://github.com/womba/mudskipper-testing /tmp/mudskipper
cp -R /tmp/mudskipper/* $MOUNTPOINT
rm -R /tmp/mudskipper
cp -R $SCRIPTPATH/1_Script/config $MOUNTPOINT/$SCRIPTPATH/1_Script

#########################
#Boot Script		#
#########################



./1_Script/ui/clear
./1_Script/ui/status x o \  \  \  \  \  \ 

arch-chroot $MOUNTPOINT .$SCRIPTPATH/1_Script/2_Boot


#########################
#Set Language Script	#
#########################


./1_Script/ui/clear
./1_Script/ui/status x x o \  \  \  \  \ 


arch-chroot $MOUNTPOINT .$SCRIPTPATH/1_Script/3_Set_Language


#########################
#Install Services Script#
#########################


./1_Script/ui/clear
./1_Script/ui/status x x x o  \  \  \  \ 

arch-chroot $MOUNTPOINT .$SCRIPTPATH/1_Script/4_Install_Services


#########################
#Enable Services Script	#
#########################



arch-chroot $MOUNTPOINT .$SCRIPTPATH/1_Script/5_Enable_Services


#########################
#Local Packages Script	#
#########################

./1_Script/ui/clear
./1_Script/ui/status x x x x o \  \  \ 


arch-chroot $MOUNTPOINT .$SCRIPTPATH/1_Script/6_Default_Apps


#########################
#Default Apps Script	#
#########################


./1_Script/ui/clear
./1_Script/ui/status x x x x x o \  \ 

arch-chroot $MOUNTPOINT .$SCRIPTPATH/1_Script/7_Local_Packages


#########################
#Create Users Script	#
#########################

./1_Script/ui/clear
./1_Script/ui/status x x x x x x o \ 


mount --bind /home/ $MOUNTPOINT$SCRIPTPATH/3_Bind
arch-chroot $MOUNTPOINT .$SCRIPTPATH/1_Script/8_Create_Users
umount $MOUNTPOINT$SCRIPTPATH/3_Bind

#########################
#Configuration Script	#
#########################

./1_Script/ui/clear
./1_Script/ui/status x x x x x x x o

arch-chroot $MOUNTPOINT .$SCRIPTPATH/1_Script/9_Configuration


##ooooooooooooooooooooooooooooooooooooooooooooo##
#						#
#		Cleaning Up			#
#						#
##ooooooooooooooooooooooooooooooooooooooooooooo##

umount ${DEVICE}1
swapoff ${DEVICE}3
umount ${DEVICE}4

./1_Script/ui/clear
./1_Script/ui/info 5 Installation\ complete\!
./1_Script/ui/clear

echo -------------------------
echo Shutdown System? \(y\/n\)
echo -------------------------
read answer

if [ "$answer" = "y" ]
then
	
	shutdown -h now

else

	exit

fi
 

